### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by italux** [italux/sentry-prometheus-exporter#8]
**Describe the bug**
When the exporter faces a connection issue with Sentry simply stop working

**To Reproduce**
1. Application simply stop working
2. Looking into the logs we found a log with the error on the title

**Expected behavior**
The application should be able to recover from this kind of issue

**Evidence**
```
2021-03-13 00:41:50,670 - 1 - INFO - werkzeug - 172.20.162.147 - - [13/Mar/2021 00:41:50] "GET /metrics/ HTTP/1.1" 200 -
2021-03-13 00:41:50,671 - 1 - INFO - exporter - exporter: cleaning registry collectors...
2021-03-13 00:41:51,252 - 1 - INFO - helpers.prometheus - metadata: sentry organization: org
2021-03-13 00:41:51,252 - 1 - INFO - helpers.prometheus - metadata: no projects specified, loading from API
2021-03-13 00:42:46,643 - 1 - ERROR - flask.app - Exception on /metrics/ [GET]
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
chunked=chunked,
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.7/http/client.py", line 1369, in getresponse
response.begin()
File "/usr/local/lib/python3.7/http/client.py", line 310, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.7/http/client.py", line 271, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
return self._sock.recv_into(b)
File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
return self.read(nbytes, buffer)
File "/usr/local/lib/python3.7/ssl.py", line 929, in read
return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:
```

**Additional context**
When running on Kubernetes (for example) environment we can add the LivenessProve to automatically restart the application if returns an error

**Comment by italux** [comment]
This issue was resolved on [v0.3.0](https://github.com/italux/sentry-prometheus-exporter/releases/tag/v0.3.0) by #22
